const express=require("express");

function createImportRouter({db,auth,n}){
  const router=express.Router();

  router.post("/",auth,async(req,res)=>{try{const rows=Array.isArray(req.body.rows)?req.body.rows:[];if(!rows.length)return res.status(400).json({error:"No CSV rows supplied."});let count=0;for(const b of rows.slice(0,2000)){const symbol=String(b.symbol||b.Symbol||b.ticker||b.Ticker||"").trim().toUpperCase(),direction=String(b.direction||b.Direction||b.side||b.Side||"").trim().toUpperCase();if(!symbol||!['BUY','SELL'].includes(direction))continue;let acct=String(b.account||b.Account||"Main Account").trim();const ac=await db("SELECT 1 FROM accounts WHERE user_id=$1 AND name=$2",[req.user.id,acct]);if(!ac.rowCount)acct="Main Account";await db(`INSERT INTO trades(user_id,account,symbol,direction,entry,stop_loss,take_profit,exit_price,quantity,risk_amount,risk_percent,profit_loss,planned_rr,actual_r,mfe_r,mae_r,max_favorable_price,max_adverse_price,rule_score,playbook_id,strategy,session,setup,entry_reason,exit_reason,emotion_before,emotion_after,mistakes,confidence,market_condition,screenshot_data,notes,trade_date) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26,$27,$28,$29,$30,$31,$32,$33)`,[req.user.id,acct,symbol,direction,n(b.entry??b.Entry),n(b.stop_loss??b.stopLoss??b.SL,null),n(b.take_profit??b.takeProfit??b.TP,null),n(b.exit_price??b.exitPrice??b.Exit,null),n(b.quantity??b.Quantity??b.qty,1),n(b.risk_amount??b.riskAmount),n(b.risk_percent??b.riskPercent),n(b.profit_loss??b.profitLoss??b.pnl??b.PnL),n(b.planned_rr??b.plannedRr),n(b.actual_r??b.actualR),n(b.mfe_r??b.mfeR),n(b.mae_r??b.maeR),n(b.max_favorable_price??b.maxFavorablePrice,null),n(b.max_adverse_price??b.maxAdversePrice,null),Math.max(0,Math.min(100,Math.round(n(b.rule_score??b.ruleScore)))),b.playbook_id?Number(b.playbook_id):null,b.strategy||"",b.session||"",b.setup||"",b.entry_reason||"",b.exit_reason||"",b.emotion_before||"",b.emotion_after||"",b.mistakes||"",Math.max(0,Math.min(100,Math.round(n(b.confidence)))),b.market_condition||"",String(b.screenshot_data||"").slice(0,4500000),b.notes||"",b.trade_date?new Date(b.trade_date):new Date()]);count++}res.json({imported:count,received:rows.length})}catch(e){console.error(e);res.status(500).json({error:"CSV import failed."})}});

  return router;
}

module.exports={createImportRouter};
